# Generated by Django 6.0 on 2025-12-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogpost_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='appointment_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.CharField(max_length=200),
        ),
    ]

